# Generated by Django 4.0.4 on 2022-10-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_tablestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
