[default]
address = "0.0.0.0"
temp_dir = "/tmp"
cli_colors = true

[debug]
port = 8000
secret_key = "EYt6qfoZBYqG8r7o2qMq04GibGmRfJZ1jOI7yPUkQ3o="

[debug.databases]
sqlite = { url = "test.db" }

[release]
#TODO SSL
port = 80
